### ISSUE TITLE
Error in provisioning; slave=KubernetesSlave

### ISSUE THREAD

**Issue by magick93** [fabric8io/fabric8-pipeline-library#116]
Without any changes to our Jenkinsfile, our build started to fail. In Jenkins log we see:

```
Feb 27, 2017 10:49:12 AM org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback call
SEVERE: Error in provisioning; slave=KubernetesSlave name: kubernetes-8ca638566b324447ad9fed48eccf8a81-33a3f3091084a, template=org.csanchez.jenkins.plugins.kubernetes.PodTemplate@6db9af81
java.lang.NullPointerException
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.combine(PodTemplateUtils.java:59)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.lambda$combine$14(PodTemplateUtils.java:118)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.combine(PodTemplateUtils.java:118)
	at org.csanchez.jenkins.plugins.kubernetes.PodTemplateUtils.unwrap(PodTemplateUtils.java:164)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.getPodTemplate(KubernetesCloud.java:375)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud.access$000(KubernetesCloud.java:87)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback.call(KubernetesCloud.java:555)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud$ProvisioningCallback.call(KubernetesCloud.java:532)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This started to happen when https://github.com/fabric8io/fabric8-pipeline-library/commit/088d36fa1b5f8d0496ac25ceb8e7046ff8cf8520 was committed. 

The Jenkinsfile is:

```
#!/usr/bin/groovy
@Library('github.com/fabric8io/fabric8-pipeline-library@master')

def failIfNoTests = ""
try {
  failIfNoTests = ITEST_FAIL_IF_NO_TEST
} catch (Throwable e) {
  failIfNoTests = "false"
}

def localItestPattern = ""
try {
  localItestPattern = ITEST_PATTERN
} catch (Throwable e) {
  localItestPattern = "*KT"
}


def versionPrefix = ""
try {
  versionPrefix = VERSION_PREFIX
} catch (Throwable e) {
  versionPrefix = "1.0"
}


def utils = new io.fabric8.Utils()
def canaryVersion = "${versionPrefix}.${env.BUILD_NUMBER}"
def label = "buildpod.${env.JOB_NAME}.${env.BUILD_NUMBER}".replace('-', '_').replace('/', '_')

mavenNode{
    checkout scm

  echo 'NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node'
  container(name: 'maven') {

    stage 'Build Release'
    mavenCanaryRelease {
      version = canaryVersion
    }

    stage 'Integration Test'
    mavenIntegrationTest {
      environment = 'Testing'
      failIfNoTests = localFailIfNoTests
      itestPattern = localItestPattern
    }
	
  }
}
```

**Comment by rawlingsj** [comment]
Your Jenkinsfile should have a version in it that maps the @Library to a tagged release version so this situation shouldn't happen.  I wonder if this Jenkinsfile is old and added to your project before we started versioning the library. 
```
@Library('github.com/fabric8io/fabric8-pipeline-library@v2.2.311')
```
That comes from this tag here https://github.com/fabric8io/fabric8-jenkinsfile-library/tree/v2.2.311

Thanks for the pointer where the issue started, I'll take a look.
